### ISSUE TITLE
Viz-3 Fixes Todo List

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#76]
- [x] Review comments on the PR: https://github.com/thevantageproject/foamviz/pull/74

**Comment by prastut** [comment]
High Priority:

- [ ] Performance Optimization - Details in another comment below (as it would need discussion)

- [x] Fix state problems: 

![image](https://user-images.githubusercontent.com/10279686/70406650-7ed40800-1a67-11ea-938d-35e10ecd7103.png)

Currently shows December 2019 data for September 2018

Medium Priority:

- [x] Making data more granular

- [x] Tooltip bugfixes, showing same value for staked value and points

- [ ] Slider - Details in another comment below

**Comment by prastut** [comment]
- [ ] Slider to become smooth. 

This won't be possible now as a slider with desired behavior isn't available as a react component. 

The best I got was https://www.npmjs.com/package/react-slider. I tried it with setting the css-transition property. Looks good when clicked on the slider anywhere, then the handle comes with a transition but when dragged manually it moves the handle with a latency. See this behavior:

![slider-transition](https://user-images.githubusercontent.com/32517802/71319875-04c16b80-24ca-11ea-91e0-b3f582de47ea.gif)

**Comment by prastut** [comment]
- [ ] Tooltip bugfixes

**Comment by prastut** [comment]
> Performance optimization. It is still very jittery to use the viz. 

Broadly classifying this into two options:-

**1. Data fetching issues**:
Combining views from Issue #75 

From @prastut 
Speculation that these would have compounding effects: 
- [x] API optimizations. 
   > Thinking from a global state that is funneling data to all the three visualizations. For eg: we fetch all the points for viz3, that solves viz1 all points + viz2 some of the cartographer points. Should we start fetching all data on the home page itself? or make an external server that updates every 10 minutes to fetch live data from FOAM and we use this server for our visualizations. 
   - [x] Fetching globe data at the homepage and updating it when the user visits viz-3. This saves the data fetching time.  

- [x] Storing fetched data in local storage.

**2. Rendering performance issues**:

> I collected some feedback from my friends. Here's the brief for required improvements in viz 3:

- Frame drop after every 2-3 second

- when time slider is paused, and changed manually, and then play is clicked, then the play icon doesn't toggle until the next iteration of the slider

- when the slider is paused, and then placed backward the towers (objects) just disappear instead of showing an animation of "unplotting". 

- for performance optimization, three modes basic, medium and advance can be shown to the user to adjust performance vs quality.
Hovering over it should describe why is it required

- Showing the unit and current iteration on the time slider, just like a ruler may be more convenient.

Need to break this down into small todos

**Comment by dhruv10** [comment]
I collected some feedback from my friends. Here's the brief for required improvments in viz 3:

- Frame drop after every 2-3 second

- when timeslider is paused, and changed manually, and then play is clicked, then the play icon doesn't toggle untill next iteration of the slider

- when the slider is paused, and then placed backwards the the towers (objects) just dissapear instead of showing animation of "unplotting". 

- for performance optimization, three modes basic, medium and advance can be shown to user to adjust performance vs quality.
Hovering over it should describe why is it required

- Showing the unit and current iteration on timeslider, just like a ruler may be more convenient.

**Comment by dhruv10** [comment]
Referencing PR #74
