### ISSUE TITLE
Viz-1 Fixes Todo List

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#78]
Medium Priority:

- [x] Add FOAM's navbar

- [x] Improve UI for "Waiting for user location message"

- [x] Remove loader at every drag

- [x] Keyboard arrow keys not working in location search box

**Comment by dhruv10** [comment]
Closed by PR #82
