### ISSUE TITLE
Viz-2 Fixes Todo List

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#79]
Medium Priority:

- [x] Add FOAM's navbar

- [x] Color of address input box gets inverted when focused

- [x] List top cartographers on viz-2 home page for a better UX

**Comment by dhruv10** [comment]
Good to have feature(s):

- [ ] Enable flyTo when switching from 2D to 3D or vice versa

**Comment by dhruv10** [comment]
Completed priority issues in PR #81
